### ISSUE TITLE
[RECIPE] Pizza topping - pear, ham...

### ISSUE THREAD

**Issue by engeir** [engeir/simple-recipes-cookbook#14]
**Is your recipe related to a category/tag/menu section? Please describe.**
Denne oppskriften er ment som topping for pizzadeigoppskriften, og burde ha `pizza` tag, samt `middag` category.

**Describe the recipe you'd like**
A recipe that is as close to a proper one as possible:

```text
---
description: "Fruktig og smakfull pizzatopping"
tag:
 - pizza
 - rask
 - lett
category:
 - middag
---

# Pizza: pære og skinke

![](https://via.placeholder.com/1280x480)

||| :timer_clock: Tid
5 min
||| :knife_fork_plate: Porsjoner
1 pizza
||| :cook: Vanskelighetsgrad
Enkel
|||

## Ingredienser

- 1 pære (gjerne litt tørre og syrlige, f.eks. en Guyot, se [her](https://www.frukt.no/ravarer/frukt/parer/))
- Spekeskinke (eller Chorizo?)
- Mozzarella
- Husker ikke resten ...

## Steg

1. Skjær pæren i ganske tynne skiver.
2. Ha i ovnen, legg gjerne på mozzarellaen mot slutten av steketiden, så blir den litt fastere.

[!ref Gå til pizzadeig](/hovedretter/pizza-deig.md)
```

**Additional context**
Her går det an å være kreativ.

**Comment by eirikjoh** [comment]
Pære, fast og litt syrlig
Mozzarella
Spinat
Spekeskinke
Blåmuggost

Bunnen forstekes med pære.
Ha på spinat, litt blåmuggost og mozzarella.
Stek til den er ferdig.
Ha på litt mer blåmuggost og spekeskinke.


Gjerne prøv å flambere skinken.
