### ISSUE TITLE
[RECIPE] Pizza

### ISSUE THREAD

**Issue by engeir** [engeir/simple-recipes-cookbook#8]
**Is your recipe related to a category/tag/menu section? Please describe.**
Pizza dough, and some pizza topping variations as well!

**Describe the recipe you'd like**
One topping could be something like:
```text
- Tomato sauce
- Pear
- Blue cheese
- Mozzarella
- Smoked ham
```

**Additional context**
Might split up into dough and topping recipes, with links to toppings (or topping tags page) in the dough recipe.

**Comment by eirikjoh** [comment]
Dough:

1000g tipo 00 flour (preferably caputo red (pizzeria, etc))
650g cool water
30g fine salt
1-5g fresh yeast (depending on proofing time)

Mix 40% of the flour and all the water utill homogenous mass. Add yeast and mix 1 min. Add salt, mix 1,5 min. Add the rest of the flour little by little. When all is added, knead for 10 min.
Let the dough rest for 5 min. 
Work the dough so it has a homogeous surface.
Let it rest in the refridgerator 0-48h.
Divide into balls of 220-275g depending on the size of your baking stone og steel.
Place in a tray, and cover so it is air tight.
Let proof for 4-10 hours depending on amount of yeast and room temperature. The dough should doubble in size.
